### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Gator911TX** [ampledata/fusedsidecar#2]
Download & Install APK: https://www.dropbox.com/s/z0tb5tl06gehvlw/app.zip?dl=0

This link is going to a deleted file dropbox notification.  Thx PD

**Comment by ampledata** [comment]
Oops, that's me, was cleaning up my dropbox, let me fix, standby!

**Comment by ampledata** [comment]
Added the debug APK to this repo, and added the correct link to the README. Also available here: https://github.com/ampledata/fusedsidecar/raw/main/app-debug.apk

Thanks for the heads-up!

**Comment by Gator911TX** [comment]
Thanks for the quick response!
